version: '3.7'
services:
  db-queue:
    container_name: db-queue
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - "postgres-data-1:/var/lib/postgresql/data"
      - "./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"

  test-db:
    container_name: test-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - "postgres-data-2:/var/lib/postgresql/data"


  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer-app:
    container_name: consumer-app
    image: ghcr.io/mark1708/consumer-app
    environment:
      DB_URL: jdbc:postgresql://db-queue:5432/test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBIT_HOST: rabbit-mq
      RABBIT_PORT: 5672
      RABBIT_USER: user
      RABBIT_PASS: password
      DB_QUEUE_LOCATION: queue_tasks_1
    depends_on:
      - db-queue
      - rabbit-mq
    ports:
      - '8090:8080'

  producer-app:
    container_name: producer-app
    image: ghcr.io/mark1708/producer-app:latest
    environment:
      DB_URL: jdbc:postgresql://db-queue:5432/test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_QUEUE_LOCATION: queue_tasks_1
    depends_on:
      - db-queue
    ports:
      - '8070:8080'

  test-app:
    container_name: test-app
    image: ghcr.io/mark1708/test-app:latest
    environment:
      DB_URL: jdbc:postgresql://test-db:5432/test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBIT_HOST: rabbit-mq
      RABBIT_PORT: 5672
      RABBIT_USER: user
      RABBIT_PASS: password
      PRODUCERS_URLS: http://producer-app:8080
    depends_on:
      - test-db
      - producer-app
    ports:
      - '8080:8080'

volumes:
  postgres-data-1:
  postgres-data-2: