version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  hazelcast-management-center:
    image: hazelcast/management-center:5.2.0
    container_name: hazelcast-management-center
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast-1,hazelcast-2
      - MC_ALLOW_MULTIPLE_LOGIN=true
      - MC_ADMIN_USER=admin123
      - MC_ADMIN_PASSWORD=p1a2s3s4w5o6r7d
    ports:
      - "8080:8080"
      -
volumes:
  postgres-data: