spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  db-queue:
    enabled: true
    config:
      create_order:
        location: queue_tasks_4
