server:
  port: 8080

spring:
  application:
    name: producer-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  db-queue:
    enabled: true
    config:
      create_order:
        location: queue_tasks_h_8
        processingSettings:
          processingMode: USE_EXTERNAL_EXECUTOR
          thread-count: 1
  threads:
    virtual:
      enabled: true