spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:change-me}
  db-queue:
    enabled: true
    config:
      create_order:
        location: queue_tasks_4
