server:
  port: 8080

spring:
  application:
    name: test-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    password: ${RABBIT_PASS}
    username: ${RABBIT_USER}

producers: ${PRODUCERS_URLS}
