server:
  port: 8080

spring:
  application:
    name: consumer-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  db-queue:
    enabled: true
    config:
      create_order:
        location: ${DB_QUEUE_LOCATION}
        processingSettings:
          processingMode: USE_EXTERNAL_EXECUTOR
          thread-count: 14
        poll-settings:
          between-task-timeout: PT0.01S # 10 MS
          no-task-timeout: PT0.1S
          fatal-crash-timeout: PT1S
          batch-size: 10
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    password: ${RABBIT_PASS}
    username: ${RABBIT_USER}
  threads:
    virtual:
      enabled: true