spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:change-me}
  rabbitmq:
    host: localhost
    port: 5672
    password: ${RABBIT_PASS:change-me}
    username: ${RABBIT_USER:user}
  db-queue:
    enabled: true
    config:
      create_order:
        location: queue_tasks_4
