server:
  port: 8081

spring:
  application:
    name: consumer-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

system:
  corePoolSize: 10